In [ ]:
!pip install numpy
!pip install matplotlib
!pip install opencv-python
!pip install scikit-image
!pip install PyWavelets

In [ ]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix
from scipy.sparse.linalg import spsolve
from scipy.io import loadmat

scipy.sparse.linalg.spsolve(A, b, permc_spec=None, use_umfpack=True) <br>
To solve the sparse linear system Ax=b, where b may be a vector or a matrix.

In [ ]:
# Example 
A = csc_matrix([[3, 2, 0], [1, -1, 0], [0, 5, 1]], dtype=float)
B = csc_matrix([[2, 0], [-1, 0], [2, 0]], dtype=float)
x = spsolve(A, B)
print(x)

  (1, 0)	1.0
  (2, 0)	-3.0


For the system of equations Ax = y, sparse solution x with lowest possible error given the output vector y and the Matrix A is to be found

In [ ]:
# def mimimizeError(A,y,m=0,epochs=1000,learning_rate=0.001):
#   N = y.shape[0]
#   for i in range(epochs):
#     y_current = spsolve(A,y)
#     cost = np.sum([data**2 for data in (y-y_current)]) / N
#     m_gradient = -(2/N) * np.sum(A * (y - y_current))
#     m_current = m_current - (learning_rate * m_gradient)
#   return m_current, cost

In [ ]:
# y = csc_matrix([[1.65],[-0.25]])
# A = csc_matrix([[-0.707,0.8,0],[0.707,0.6,-1]])
# X, cost = mimimizeError(A,y)

In [ ]:
# A = csc_matrix([[3, 2, 0], [1, -1, 0], [0, 5, 1]], dtype=float)
# B = csc_matrix([[2, 0], [-1, 0], [2, 0]], dtype=float)
# X, cost = mimimizeError(A,y)

In [ ]:
# from scipy.io import loadmat
# annots = loadmat('Task1.mat')
# annots.keys()

We couldn't apply the above method as the matrix A isnt a sq matrix. So trying other approaches:

We can try to find the sparse matrix x using greedy method:

In [ ]:
#Ax = y

In [ ]:
y = np.array([[1.65],
     [-0.25]])
A = np.array([[-0.707,0.8,0],
     [0.707,0.6,-1]])

In [ ]:
A.shape

(2, 3)

In [ ]:
#Assume an x with random numbers  and is sparse
#For Task 1.1, x has to be 3 x 1 dimension
x = np.array([[1],[0],[1]])


In [ ]:

#Find number of smallest number of non zero coefficients or support
#But solving by L1 norm is more practical
x_ = np.linalg.norm(x,1)

In [ ]:
e=100
l=1
l2norm=0
min_err = 10000
min_err_1st_i=0

In [ ]:
for i in range(100) or abs(e)<0.1:
    e = np.linalg.norm(np.dot(A,x)-y)
    

In [ ]:
#Trying the greedy way
#Step 1
def find_1st_best_atom(A,y,x=x ):
  n = A.shape[1]
  l2norm=0
  min_err = 10000
  for i in range(n):
    l2norm = np.linalg.norm(np.dot(A[:,i].reshape((2,1)),x[i,:].reshape((1,1)))-y,2)
    if(l2norm<min_err):
      min_err= l2norm
      min_err_1st_i= i
    
  return i,min_err



In [ ]:
#i,min_err = find_1st_best_atom(A,y)

In [ ]:
#we must keep track of the best atom indices 
known_best_atoms_i = []

In [ ]:
#Step 2
#find other atoms that will minimise the error 
def find_other_atoms(A,y,min_err,x=x ):
  n = A.shape[1]
  min_err_other_i = -1
  for i in range(n):
    if(i not in known_best_atoms_i):
      l2norm = np.linalg.norm(np.dot(A[:,i].reshape((2,1)),x[i,:].reshape((1,1)))-y,2)
      if(l2norm+min_err<min_err):
        min_err = l2norm + min_err
        min_err_other_i= i
    
  return min_err_other_i,min_err

In [ ]:
#Limit of max number of non zero values in x
S_max = 2
i1,min_err = find_1st_best_atom(A,y)
known_best_atoms_i.append(i1)
print(known_best_atoms_i)
for j in range(S_max-1):
  i_other,min_err = find_other_atoms(A,y,min_err)
  if(i_other!=-1):
    known_best_atoms_i.append(i_other)
  print(known_best_atoms_i)

[2]
[2]


In [ ]:
#Make other elements in x whose row numbers are not in 
#known_best_atoms as 0 
def make_sparse_x(x,nonzero_inices = known_best_atoms_i):
  x_rows = x.shape[0]
  for i in range(x_rows):
    if(i not in nonzero_inices):
      x[i,0]=0
  return x

In [ ]:
sparse = make_sparse_x(x)
sparse


array([[0],
       [0],
       [1]])

In [ ]:
np.dot(A,x)

array([[ 0.],
       [-1.]])

In [ ]:
#1.2:
#First let's get

In [ ]:
!pip install PyDrive


In [ ]:
# Import PyDrive and associated libraries.
# This only needs to be done once per notebook.
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Download a file based on its file ID.
#https://drive.google.com/file/d/1ondpZi7Rbu_QAkuu6wvGNEYPERnkIEOZ/view?usp=sharing
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz
file_id = '1ondpZi7Rbu_QAkuu6wvGNEYPERnkIEOZ'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('Task1.mat')  
# print('Downloaded content "{}"'.format(downloaded.GetContentString()))

In [ ]:
import scipy.io
mat = scipy.io.loadmat('Task1.mat')

In [ ]:
# mat.items()

In [ ]:
mat['A'].shape

(32, 64)

In [ ]:
mat['y'].shape

(32, 1)

In [ ]:
#x is of dimension (64,1)
x= np.random.randn(64,1)

In [ ]:
A = mat['A']
y = mat['y']

In [ ]:
#All the functions together for this q
A_i = A.shape[0]
A_j = A.shape[1]
x_i = x.shape[0]
x_j = 1

#Step 1
def find_1st_best_atom(A,y,x=x ):
  n = A.shape[1]
  l2norm=0
  min_err = 10000
  for i in range(n):
    l2norm = np.linalg.norm(np.dot(A[:,i].reshape((A_i,1)),x[i,:].reshape((1,x_j)))-y,2)
    if(l2norm<min_err):
      min_err= l2norm
      min_err_1st_i= i
    
  return i,min_err

#we must keep track of the best atom indices 
known_best_atoms_i = []

#Step 2
#find other atoms that will minimise the error 
def find_other_atoms(A,y,min_err,x=x ):
  n = A.shape[1]
  min_err_other_i = -1
  for i in range(n):
    if(i not in known_best_atoms_i):
      l2norm = np.linalg.norm(np.dot(A[:,i].reshape((A_i,1)),x[i,:].reshape((1,x_j)))-y,2)
      if(l2norm+min_err<min_err):
        min_err = l2norm + min_err
        min_err_other_i= i
    
  return min_err_other_i,min_err

#Limit of max number of non zero values in x
S_max = 2
i1,min_err = find_1st_best_atom(A,y)
known_best_atoms_i.append(i1)
print(known_best_atoms_i)
for j in range(S_max-1):
  i_other,min_err = find_other_atoms(A,y,min_err)
  if(i_other!=-1):
    known_best_atoms_i.append(i_other)
  print(known_best_atoms_i)

#Make other elements in x whose row numbers are not in 
#known_best_atoms as 0 
def make_sparse_x(x,nonzero_inices = known_best_atoms_i):
  x_rows = x.shape[0]
  for i in range(x_rows):
    if(i not in nonzero_inices):
      x[i,0]=0
  return x

[63]
[63]


In [ ]:
sparse = make_sparse_x(x)
sparse

array([[ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0

In [ ]:
np.linalg.norm(np.dot(A,x)-y,2)

2.4736118726506158